language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - PHALCON_VERSION="2.0.1"
services:
  - redis-server
  - mysql
before_script:
  - mysql -e 'create database phalcon_poll;'
  - mysql -e "GRANT ALL PRIVILEGES ON phalcon_poll.* TO 'phalcon_poll'@'localhost' IDENTIFIED BY '';"
  - ./travis/install-php-extension.sh ${PHALCON_VERSION}
  - phpenv config-add travis/php.ini
  - composer install
script: cd tests && phpunit --configuration phpunit.xml --coverage-text ./
